# -*- coding: utf-8 -*-
"""hospital_info.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwZwbn_b6wtq-jQ1He1lcvG_Ala4-9DR
"""

import pandas as pd
from google.colab import drive
import os

drive.mount('/content/drive')

path = '/content/drive/MyDrive/Colab Notebooks/'

file1 = path + '1.병원정보서비스(2026.3.).xlsx'
file2 = path + '4.의료기관별상세정보서비스_02_세부정보(2026.3.).xlsx'
file3 = path + '5.의료기관별상세정보서비스_03_진료과목정보(2026.3.).xlsx'

print("데이터를 불러오는 중입니다. 잠시만 기다려주세요...")

df_basis = pd.read_excel(file1)
df_detail = pd.read_excel(file2)
df_subject = pd.read_excel(file3)


df_merged = pd.merge(df_subject, df_basis[['암호화요양기호', '전화번호', '좌표(X)', '좌표(Y)', '종별코드', '종별코드명']],
                     on='암호화요양기호', how='left')

time_cols = ['암호화요양기호'] + [col for col in df_detail.columns if '진료시작시간' in col or '진료종료시간' in col]
df_detail_times = df_detail[time_cols]
df_final = pd.merge(df_merged, df_detail_times, on='암호화요양기호', how='left')

def format_time(t):
    if pd.isna(t) or str(t).strip() == '':
        return None

    t_str = str(t).replace('.0', '').strip()
    if not t_str.isdigit():
        return t_str

    t_str = t_str.zfill(4)
    if len(t_str) == 4:
        return f"{t_str[:2]}:{t_str[2:]}"
    return t_str

days = ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일']
for day in days:
    start_col = f'진료시작시간_{day}'
    end_col = f'진료종료시간_{day}'

    if start_col in df_final.columns and end_col in df_final.columns:
        df_final[start_col] = df_final[start_col].apply(format_time)
        df_final[end_col] = df_final[end_col].apply(format_time)

        df_final[f'{day} 운영시간'] = df_final.apply(
            lambda row: f"{row[start_col]} ~ {row[end_col]}"
            if pd.notna(row[start_col]) and pd.notna(row[end_col]) else '휴진/정보없음',
            axis=1
        )

# 컬럼에 '종별코드', '종별코드명' 추가
columns_to_keep = {
    '요양기관명': '병원 이름',
    '종별코드': '종별코드',
    '종별코드명': '종별코드명',
    '진료과목코드': '진료과목코드',
    '진료과목코드명': '진료 과목',
    '전화번호': '병원 전화번호',
    '좌표(X)': '병원 좌표(x)',
    '좌표(Y)': '병원 좌표(y)'
}
day_time_cols = [f'{day} 운영시간' for day in days]

df_result = df_final[list(columns_to_keep.keys()) + day_time_cols].rename(columns=columns_to_keep)

output_zip_path = '/content/hospital_info2.zip'

df_result.to_csv(output_zip_path,
                 index=False,
                 encoding='utf-8-sig', # 한글 깨짐 방지
                 compression=dict(method='zip', archive_name='hospital_info2.csv'))

print(f"작업 완료! 파일이 생성되었습니다: {output_zip_path}")

# 자동 다운로드
from google.colab import files
files.download(output_zip_path)